FROM remche/openfoam:alpha

USER 0
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      python3-pip \
      python3-setuptools

RUN pip3 install wheel
RUN pip3 install fluidfoam
USER 1000
